'use client';

import React from 'react';
import { ApolloProvider } from '@apollo/client';
import { ThemeProvider } from 'styled-components';
import client from '../lib/apolloClient';
//import GlobalStyles from '../styles/GlobalStyles';

const theme = {
  colors: {
    primary: '#0070f3',
    secondary: '#1c1c1e',
    background: '#f5f5f7',
    text: '#333',
  },
};

/*export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};*/

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ApolloProvider client={client}>
          <ThemeProvider theme={theme}>
            {/* <GlobalStyles /> */}
            {children}
          </ThemeProvider>
        </ApolloProvider>
      </body>
    </html>
  );
}
